---
- hosts: all
  become: true
  tasks:

#  - name: Install Python3
#    apt:
#      name: python3
#      state: latest
#
#  - name: Install Pip3
#    apt:
#      name: python3-pip
#      state: latest

#  - name: Set Pip3 as default python
#    command: echo "alias python=/usr/local/bin/python3" >> ~/.bashrc
#  - command: echo "alias pip=/usr/local/bin/pip3" >> ~/.bashrc

#   - name: Install Java OpenJDK
#     package:
#        name:
#          - "{{ java_package }}"
#        state: latest

  
  
#- name: Create Motd with variable from config.yaml file
#  hosts: all
#  become: true
#  vars_files:
#    - config.yaml
#  tasks:
#    - name: Create Motd file with variable text or default text if not defined in config.yaml file
#      template:
#        src: motd.j2
#        dest: /etc/motd  
  
- name: Create User with variable from config.yaml file
  hosts: all
  become: true
  vars_files:
    - config.yaml
  tasks:
    - name: Create User with variable username from config.yaml file or default username if not defined in config.yaml file
      user:
        name: "{{ username | default('floresCentOS') }}"
        state: present
